### ISSUE TITLE
Capture OS signals during prompts

### ISSUE THREAD

**Issue by marcushultman** [c4spar/deno-cliffy#105]
I have an application that needs to capture and handle OS signals (SIGINT), but it seems like [inputs](https://github.com/c4spar/deno-cliffy/blob/357db7fd6a741619c40fac285cf00602b75dd16b/prompt/_generic_input.ts#L67) and [Select](https://github.com/c4spar/deno-cliffy/blob/357db7fd6a741619c40fac285cf00602b75dd16b/prompt/select.ts#L83) has hardcoded logic for control+c, ending with a `Deno.exit(0)`. I would like to be able to tell cliffy to not exit immediately, but to give me control to properly clean things up before exiting. I'd be up for making a PR for any solution that is of interest. One idea is to offer a callback option.

**Comment by c4spar** [comment]
Hi @marcushultman,

Yes, we should definitely improve that! And if you want to make a PR this would be great 👍 But i'm not shure if we should use a callback method.

I think the best would be if it were possible to emit a SIGINT signal on `ctrl+c`. Then you can simply register a handler with `Deno.signal()` or `Deno.signals.interrupt()`. But I haven't found a way to emit a signal yet.

If we use a callback method, than you have to register two SIGINT handler. One with the prompt method and one with `Deno.singal()` in case the prompt isn't running actually.

**Comment by marcushultman** [comment]
@c4spar `Deno.kill(Deno.pid, Deno.Signal.SIGINT);` would work (it's even used in [`std/signal` tests](https://github.com/denoland/deno/blob/df02e315075456f8d5f75472abbb1fa81e237827/std/signal/test.ts)). I'll experiment some more on my own fork by raising a signal (the [callback](https://github.com/marcushultman/deno-cliffy/tree/exit-option) solution I sketched up works, but indeed requires two handlers just as you say.

**Comment by marcushultman** [comment]
Made a PR https://github.com/c4spar/deno-cliffy/pull/106

**Comment by c4spar** [comment]
Awesome! thanks for this PR @marcushultman.

This works great but i'm also not so happy with the `--allow-run` flag. Because this forces the user to disable the sandbox mode of deno and indicates that we want to run a child process but we only want to kill our own process.
Deno should provide a way to allow a script to kill itself with a SIGINT without the need of the `--allow-run` flag. 

We could ask the user for the run permissions berfor calling `Deno.kill()` but than it would be possible the user disagrees and the sigint event doesn't fires and there will be also no sandboxing mode.

I found also an issue with the SIGINT handler. The default SIGINT actions wan't be restored after calling sig.dispose() atm.
For example, if you exit following script with `ctrl+c`, `ctrl+c` is no longer working for the shell prompt and other programms like `tail -f <file-name>`.
```typescript
import { Input } from "https://raw.githubusercontent.com/marcushultman/deno-cliffy/raise-signal/prompt/input.ts";

const sigint = Deno.signals.interrupt();

(async () => {
  for await (const _ of sigint) {
    sigint.dispose();
    Deno.exit(0);
  }
})();

const name: string = await Input.prompt("What's your github user name?");
console.log({ name });
sigint.dispose();
```
There is already a deno issue for this: https://github.com/denoland/deno/issues/7164

Maybe we should first implement the callback solution and as soon as the above bug is fixed and there is a way to trigger the SIGINT event without the need of the `--allow-run` flag, we can implement the new version. We can do this without a breaking change. If a callback is passed to the prompt, the callback will be executed, otherwise the kill api is used.

What do you think?

**Comment by c4spar** [comment]
Another issue is, `Deno.kill()` doesn't work on windows as mentioned in the documentation: `This functionality currently only works on Linux and Mac OS.`
https://doc.deno.land/builtin/unstable#Deno.kill

**Comment by marcushultman** [comment]
I think it's not unreasonable to want a way to `raise` a signal from within Deno itself, and I know the Deno core team are susceptible for ideas that improve stuff like this.

Another issue I found is also that cliffy prevents other tasks such as suspending the process (ctrl+z). Not sure what options there are.

**Comment by c4spar** [comment]
I have opend an deno issue https://github.com/denoland/deno/issues/8299. Let's see what they will say.

**Comment by marcushultman** [comment]
@c4spar I've opened another issue https://github.com/denoland/deno/issues/8343 that would help solve this. If we could use another TTY mode that forwards keystrokes, but handles interrupts/suspend, the whole problem disappears.

**Comment by c4spar** [comment]
Cool, that would be even better! thanks @marcushultman
