### ISSUE TITLE
Expose Command.error() so that post validation parsing of options can display a similar error when called manually

### ISSUE THREAD

**Issue by rbeesley** [c4spar/deno-cliffy#226]
Referencing https://github.com/c4spar/deno-cliffy/blob/d93ad7d8033dd5a630e6bad05722f96392e7c54e/command/command.ts#L1250-L1267, it would be a nice feature to be able to perform my own validation after using `Command.parse()`, so that I can throw a custom error which also displays the help with the same formatting. Throwing an error, even a `ValidationError`, after parsing is complete appears to only be handled as a general exception and I didn't see an easy way to invoke that through the API. Something like `Command.error(new ValidationError("Message"));` would probably be ideal for that purpose.

**Comment by c4spar** [comment]
@rbeesley yeah it would definitely make sense to expose this function and it was already exposed in an early version but I reverted it for the time being because the build errors required some more investigations. But I agree we should addressed this in the next time to keep error messages consistent!
