### ISSUE TITLE
Command with global option parse error

### ISSUE THREAD

**Issue by codehz** [c4spar/deno-cliffy#241]
```typescript
import { Command } from "https://deno.land/x/cliffy@v0.19.2/command/mod.ts";

await new Command()
  .name("demo")
  .version("0.0.0")
  .description("DEMO")
  .option("--watch", "watch mode", {
    global: true,
  })
  .command("build", new Command().description("Build."))
  .action(console.dir)
  .parse(Deno.args);
```

input `deno run -A file.ts --watch build`
error:
```
error: Unknown command "build". Did you mean command "build"?
```

**Comment by c4spar** [comment]
thx @codehz for creating the issue!
The problem is that cliffy assumes that the sub command is the first argument. If you put your flags after your sub command, then your command works: `deno run file.ts build --watch`.
I will check if I can fix this behavior or at least display a better error message.

**Comment by c4spar** [comment]
This is now possible since [v0.25.2](https://github.com/c4spar/deno-cliffy/releases/tag/v0.25.2)
