### ISSUE TITLE
Support did-you-mean for invalid command

### ISSUE THREAD

**Issue by hojongs** [c4spar/deno-cliffy#278]
# Description

In README(https://github.com/c4spar/deno-cliffy/tree/main/command#-did-you-mean)

> cliffy prints some suggestions, when the user executes an invalid command, or the developer has a typo in the name of a type.

Assume there is my command `cook pizza`, I expected the result like this below.

```sh
$ cook pizza # if I ran a correct command
Success: Cooked pizza!
$ cook pizz # if I ran a wrong command
error: Unknown command "pizz". Did you mean command "pizza"?
```

**Expected behavior: prints a did-you-mean error message
Actual behavior: exit without any error message**

It works fine with unknown options, but it doesn't work with unknown commands.

Example implementation code of cook command

```ts
import { Command } from "https://deno.land/x/cliffy@v0.19.5/command/mod.ts";

const command = new Command();
command
  .name("pb")
  .arguments("<command>")
  .command("pizza", ...)
  .parse(Deno.args);
```

## Clarification

I thought the document said did-you-mean works for invalid commands.

1. Was the document wrong? (or I misunderstood?)
2. Is this bug?

I tested it with cliffy@v0.19.1 and 0.19.5, thanks!

**Comment by c4spar** [comment]
Hi @hojongs,
the reason why you don't get an error with `cook pizz` is, because you have defined an argument with `.arguments("<commands>")`. This means if you call `cook pizza` the pizza command is executed with no arguments, but if you call `cook pizz` the main command is executed with `pizz` as argument which is allowed because the main command takes an argument.
You need to remove `.arguments("<command>")` then you will get the expected error.

**Comment by hojongs** [comment]
Thank you for your kind explanation! I fully understood!
I missed [this section](https://github.com/c4spar/deno-cliffy/tree/main/command#executable-sub-commands) to implement to sub-commands. 😓  (and next section)

**Comment by hojongs** [comment]
After removing the `.arguments("<command>")`, My issue is resolved! Thank you!
(Also https://github.com/c4spar/deno-cliffy/discussions/179 was very helpful to keep to show top-level help message)
