### ISSUE TITLE
Create a command with unkown options

### ISSUE THREAD

**Issue by oganexon** [c4spar/deno-cliffy#43]
I'd like to make a command that runs a process in Deno.
Kind of like `npm run test -- --grep="pattern"`.

I would then get the args and feed them with `Deno.run` to another process.

But I can't determine the options in advance, how can I create such command?

**Comment by c4spar** [comment]
Hi @oganexon,

You can use the [.stopEarly()](https://github.com/c4spar/deno-cliffy/tree/master/packages/command#stop-early) method as descriped in the readme to pass unkown options to your command. If enabled, all options, starting from the first none option argument, will be passed as arguments to the action handler.

Literal arguments won't be passed to the action handler atm, but this feature is in progress.

**Comment by oganexon** [comment]
Great, almost there
If i follow the example I can do:
```bash
$ deno run https://deno.land/x/cliffy/examples/command/stop-early.ts -d warning server -p 80
options: { debugLevel: "warning" }
script: server
args: [ "-p", "80" ]
```

But how can I do:
```bash
$ deno run https://deno.land/x/cliffy/examples/command/stop-early.ts warning server -p 80
```

**Comment by c4spar** [comment]
This is not possible with `.stopEarly()`, because `.stopEarly()` needs to know which options belongs to the command and which to the arguments. You need an argument to separate these options.

In your example, `--foo` will be interpreted as option from the `stop-early.ts` command and `warning server -p 80` will be passed as arguments because `warning` is the first none option argument.

There is also another method called `.useRawArgs()`. If you call this method, all options are interpreted as arguments. But this will also disable the handling of all build in options like `--help` and `--version`.

**Comment by oganexon** [comment]
Perfect, I managed to have help and get the args
```ts
export class RunCommand extends DefaultCommand {
  public constructor() {
    super();

    this.description(desc)
    .useRawArgs()
    .action((_, ...args) => {
      if (["-h", "--help", "help"].includes(args[0])) {
        Deno.stdout.writeSync(new TextEncoder().encode( this.getHelpCommand().getHelp() ) );
        Deno.exit()
      }
      console.log(args)
    });
  }
}
```
