### ISSUE TITLE
Command fails when argument value contains dashes

### ISSUE THREAD

**Issue by jjoynson-iw** [c4spar/deno-cliffy#466]
Deno version: 
```deno 1.23.3 (release, aarch64-apple-darwin)
v8 10.4.132.8
typescript 4.7.4
```
Cliffy version:
0.25.2

I'm receiving errors when passing arguments with a value that contain dashes.
```
error: Unknown option "- ". Did you mean option "-h"?
```

![image](https://user-images.githubusercontent.com/99184730/194839803-1cfb3d4e-4336-4eea-aef5-3becce2927a2.png)

I've made a simply script which reproduces this issue:
https://gist.github.com/jjoynson-iw/c9f56eb112038b665f60cd20e0128fa0

Working: 
```
deno run https://gist.githubusercontent.com/jjoynson-iw/c9f56eb112038b665f60cd20e0128fa0/raw/764be2f73c53dad5a2329137286dfaf3f46d0194/cliffy-command-dash-issue.ts --name 'test' 
```

Errors: 
```
deno run https://gist.githubusercontent.com/jjoynson-iw/c9f56eb112038b665f60cd20e0128fa0/raw/764be2f73c53dad5a2329137286dfaf3f46d0194/cliffy-command-dash-issue.ts --name '- test' 
```

Changing the quote from single to double quote made not difference. 

Changing the command input from square brackets (`-n, --name [name]`) to angle brackets (`-n, --name <name>`) makes the command work correctly.

**Comment by c4spar** [comment]
Hi @jjoynson-iw,

the solution for this would be to use an equals sign for the value like this `--name='- test'`. Otherwise cliffy cannot detect if this is a value or an option. You can also require an equals sign for the option if you define it like this `-f, --foo=[val]`.
But for some reason the value gets ignored if it's prefixed with `-` and an equals sign is used. Will look into it.
