### ISSUE TITLE
Using a subcommand looses the typing of the options

### ISSUE THREAD

**Issue by sigmaSd** [c4spar/deno-cliffy#529]
```ts
new Command()
  .command("r", "")
  .option("-p <p:string>", "")
  .parse(Deno.args).then((c) => c.options.p);
```

c.options.p have type unknown instead of string | undefined, if I remove the subcommand the type is inferred correctly

It could be that I'm using this api wrong though

**Comment by c4spar** [comment]
This is actually expected behaviour. if the command has sub commands, the return type from the parse method is unknown, because cliffy cannot know which command will be executed. If you use an action handler the types should be correct inside the action handler. I think it would be too expensive if I return an union type with all possible results from all sub commands.

**Comment by sigmaSd** [comment]
I see thanks

One more unrelated question, can I get parse to allow remaining arguments, std parse `_` ? and then access them ?

**Comment by c4spar** [comment]
No this is currently not possible but feel free to open an issue. I think we could add an `.allowUnknown()` method or sth like that to disable validation of unknown options.
