### ISSUE TITLE
Release cadence

### ISSUE THREAD

**Issue by andrewthauer** [c4spar/deno-cliffy#629]
First off, thanks for the excellent CLI framework!

I'm curious if there is a particular schedule or cadence for releases? It seems there have been quite a few code changes between the last release v0.25.7 (6 months ago).

**Comment by c4spar** [comment]
Sorry for the long time I haven't released a new version! Normally I try to release as often as possible.

My plan was to make only one more release with breaking changes before 1.0 but since I had already merged a breaking change but also wanted to get some other things done with breaking changes that were not easy to implement, the release was blocked.
I also had a lot to do in my private life and was on a long trip, so I didn't have much time to solve the last issues.

But most things are solved now and I'm currently doing a final check before I release 1.0.0-rc.1 😉

**Comment by andrewthauer** [comment]
No problem at all. There isn't a particular feature or issue I'm waiting on, was more just curious. Thanks!
