### ISSUE TITLE
`this` undefined in command/subcommand action

### ISSUE THREAD

**Issue by leighmcculloch** [c4spar/deno-cliffy#756]
Cliffy: 1.0.0-rc.7
Deno: 2.0.0

When using `this` inside a command/subcommand action, it appears to be `undefined`.

```ts
import { Command } from "jsr:@cliffy/command@1.0.0-rc.7";

const root = new Command()
  .name("mycli")
  .description("Description...")
  .globalOption("-q, --quiet", "Make the output quiet")
  .action(() => this.showHelp());
```

```console
$ deno main.ts
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'showHelp')
  .action(() => this.showHelp());
                     ^
    at Command.actionHandler (file:///Users/leighmcculloch/Code/denostellar/main.ts:7:22)
    at Command.execute (https://jsr.io/@cliffy/command/1.0.0-rc.7/command.ts:1940:18)
    at async Command.parseCommand (https://jsr.io/@cliffy/command/1.0.0-rc.7/command.ts:1772:14)
    at async file:///Users/leighmcculloch/Code/denostellar/main.ts:19:1
```

According to previous issues, `this` binding was added:
- https://github.com/c4spar/deno-cliffy/issues/28
- https://github.com/c4spar/deno-cliffy/commit/461145fe9355c16d61fcbf6d40bc48cf39c3095a

**Comment by 0f-0b** [comment]
[Arrow functions](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Functions/Arrow_functions) don't have their own `this` bindings, so here `this` refers to that of the module (which is always `undefined`) rather than of the action function. To fix this, you can change the arrow function to a [`function` expression](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/function).

**Comment by leighmcculloch** [comment]
Ah, thank you for kindly showing me the way!
